# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "l+v/XplBe+Zu8NjE4e6QKi8SoRXX0yaR72v2iCeuhUmKHTZxvwG3Ici4fsxhlqwFvhoNDhV9a+L0QI8lasfoVeGdiJKxgiiqDd/e95Suc+Tj7PZ1ZTXNF7LiSUBHoCYLPNlQhY0sXKf46nnuxkvOlXKKuZA12KRxM9fH/yDUPwBL25jBPkEBox2cf9wzCJ4CoikhNcz5ogqtHYD6AQ1KwPc03YeLgdEsDrqROM1VeAwxOx4bH763h+HmI7/8NgvnX58EDobyeEnzr1VDxvM9Uk5KgArzru/4AGVNEeNV+IvfMXQXbWCHVtMRWblRVZ3+4ElVkG47wHaHBlv97EYjIei5ba5s1X1LWBXPoDZEgrZHRrM2xltGqLtqpNS+Ib7+xRwNTdGeNAwBZwPhM8BjHmviQXofMRLtU2nZK8AyGKK36uVleKLy2rCeRLRJ4C6I/EuhS/6GOQGwGMAdPYmLHFrkvvCixyQLZVL12rnPRP5/0JaMd4lhPrHciGuck7oOLQIevAiRbbDVg03K6M04F88bOJQZ+7H0+ejBS1SN+6voVsPtZ1CTopNx/Fd7LkESNQH3SRy2hg3BmPbSCBsO0fEr5DtYGmY1wfYgnXIcrPFV+WDJhIedn6SbkoEwVppMrmB2okUQvT6TBLer3n4D8MGxWneFN0rSTzE6AJ3P4+M="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
