travis:
  secure:
    BINSTAR_TOKEN: P8yBy6cFHHbLjf5hv1dgTr6f4iXQGGcgZ3KSls5TG9QPM99ZgUuxu7oXm878/UgieS6QspyP93WJY43Jw87Kslz5bg7vdnSAvZupFxBxJYqmieHcvZPHHyfAxI/T/yDufPiIQTSsZY8iOiY2HnRC/JTcOswkTebga1LgQBlRw2SoP/tAkpgENeCW1FvfqaOiSJR92pRdsVIOWjpkLW5dc+XTlhIFkpamS/0hwQE1J0Q4hA034AEIhEqwLCMY619LVcM+JHZVCwxo9qI17LtKtMR+VT6d0gEBIiGjJLSmlsrP2n/uLejjbLMStV/aFfMtG0YM5afC2tlKV8ED88f0w0Avwl3FzDcVZVQ5AVXXs28+Ix+px8X899jdJHCLEtnRvI6TmC4smOvCpHVmoq+DKbY1sA86JPfcblyztUJlu62+xcLalQCKWMqu7ldW/6GJQBQi7bctOQ3ETGTESjECU/zeKCggjct2yPltpJNFXCzWcPcscZtLKWXH4HUtLGhuWeI60+/7POlED5p/eZfbMVkpO9ADWZzF304VSWA/JDeb4i/Ic9M4xXYfSywHKqzep/nqmKT2WMQMrUnluWvdE5gxQtJs1UUvX++Gsj07qrs74i9k7dxOZ9mkxP7LrcNJl7AfGRZNdOQ4NFG3eT5LYWn/iYO/eL+l6p0kV/AtHTY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
