travis:
  secure:
    BINSTAR_TOKEN: l+v/XplBe+Zu8NjE4e6QKi8SoRXX0yaR72v2iCeuhUmKHTZxvwG3Ici4fsxhlqwFvhoNDhV9a+L0QI8lasfoVeGdiJKxgiiqDd/e95Suc+Tj7PZ1ZTXNF7LiSUBHoCYLPNlQhY0sXKf46nnuxkvOlXKKuZA12KRxM9fH/yDUPwBL25jBPkEBox2cf9wzCJ4CoikhNcz5ogqtHYD6AQ1KwPc03YeLgdEsDrqROM1VeAwxOx4bH763h+HmI7/8NgvnX58EDobyeEnzr1VDxvM9Uk5KgArzru/4AGVNEeNV+IvfMXQXbWCHVtMRWblRVZ3+4ElVkG47wHaHBlv97EYjIei5ba5s1X1LWBXPoDZEgrZHRrM2xltGqLtqpNS+Ib7+xRwNTdGeNAwBZwPhM8BjHmviQXofMRLtU2nZK8AyGKK36uVleKLy2rCeRLRJ4C6I/EuhS/6GOQGwGMAdPYmLHFrkvvCixyQLZVL12rnPRP5/0JaMd4lhPrHciGuck7oOLQIevAiRbbDVg03K6M04F88bOJQZ+7H0+ejBS1SN+6voVsPtZ1CTopNx/Fd7LkESNQH3SRy2hg3BmPbSCBsO0fEr5DtYGmY1wfYgnXIcrPFV+WDJhIedn6SbkoEwVppMrmB2okUQvT6TBLer3n4D8MGxWneFN0rSTzE6AJ3P4+M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
